M48
; DRILL file KiCad 10.0.4 date 2026-07-23T21:57:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T21:57:46+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X56.6Y-69.61
X56.6Y-75.39
T2
X55.0Y-55.0
X55.0Y-90.0
X130.0Y-55.0
X130.0Y-90.0
M30
